const ini = require('ini');
const fs = require('fs');
const path = require('path');

function getHostsToRsync() {
  // file generated by ansible
  // eslint-disable-next-line global-require, import/no-unresolved
  const rsyncConfig = require('../../../deployment/rsync_config');

  const hosts = ini.parse(fs.readFileSync(path.resolve(__dirname, '../../../deployment/hosts.ini'), 'utf-8'));

  const { host, type } = rsyncConfig;
  const number = host.charAt(6);
  const rsyncHosts = Object.keys(hosts[type]).filter((k) => !k.includes(host) && k.charAt(6) === number);

  return rsyncHosts.map((rh) => {
    const value = hosts[type][rh];
    // Parse the host configuration line to extract rsyncIP
    const hostConfig = value.split(' ').reduce((acc, item) => {
      const [key, val] = item.split('=');
      if (key && val) {
        acc[key] = val;
      }
      return acc;
    }, {});

    // Use rsyncIP if available, otherwise fall back to ansible_host
    return hostConfig.rsyncIP || hostConfig.ansible_host;
  });
}

module.exports = {
  getHostsToRsync,
};
