const ini = require('ini');
const fs = require('fs');
const path = require('path');

// file generated by ansible
const rsyncConfig = require('../../../deployment/rsync_config');

const hosts = ini.parse(fs.readFileSync(path.resolve(__dirname, '../../../deployment/hosts.ini'), 'utf-8'));

function getHostsToRsync() {
  const { host, type } = rsyncConfig;
  const rsyncHosts = Object.keys(hosts[type]).filter((k) => !k.includes(host));
  return rsyncHosts.map((rh) => {
    const value = hosts[type][rh];
    return value.substring(0, value.indexOf(' '));
  });
}

module.exports = {
  getHostsToRsync,
};
