---
- name: Install and configure FDM
  hosts: "main_dev_fdm_servers"
  become: yes

  tasks:
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.package:
        name:
          - software-properties-common
          - certbot
          - haproxy
          - dirmngr
          - gnupg
          - apt-transport-https
          - ca-certificates
          - build-essential
          - libssl-dev
          - curl
          - python3-pip
        state: present

    - name: Add NodeSource repository key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_22.x {{ ansible_distribution_release }} main"
        state: present

    - name: Install Node.js 22.x
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Install PM2 globally using NPM
      command: npm install -g pm2

    - name: Ensure directory exists
      ansible.builtin.file:
        path: /etc/ssl/fluxapps
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: Get dhparam
      ansible.builtin.get_url:
        url: https://ssl-config.mozilla.org/ffdhe4096.txt
        dest: /etc/haproxy/dhparam
        mode: '0644'

    - name: Clone FDM
      ansible.builtin.git:
        repo: https://github.com/RunOnFlux/flux-domain-manager.git
        dest: flux-domain-manager
        version: main
        force: yes
        update: yes
        clone: yes
        depth: 1
        accept_hostkey: yes

    - name: Copy default.js config to FDM
      ansible.builtin.template:
        src: default.js.j2
        dest: flux-domain-manager/config/default-0.js
        mode: '0644'
      vars:
        manageCertificateOnly: "false"
        appSubDomain: "app2"
        useSubset: "false"
        manageApps: "false"
        fdmAppDomain: "fdm-lb-2-1.runonflux.io"
        startSubset: "0"
        endSubset: "F"
        uiName: "devhome"
        apiName: "devapi"

    - name: Install Dependencies FDM
      command: npm install
      args:
        chdir: flux-domain-manager

    - name: start FDM
      command: sudo pm2 restart FDM
      args:
        chdir: flux-domain-manager
      environment:
        NODE_ENV: production
        NODE_CONFIG_DIR: flux-domain-manager/config

